/*
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration.ui.contentassist

import org.modelversioning.emfprofile.decoration.ui.contentassist.AbstractEMFProfileDecorationLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EMFProfileDecorationLanguageProposalProvider extends AbstractEMFProfileDecorationLanguageProposalProvider {
}
