/**
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration.validation;

import org.modelversioning.emfprofile.decoration.validation.AbstractEMFProfileDecorationLanguageValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EMFProfileDecorationLanguageValidator extends AbstractEMFProfileDecorationLanguageValidator {
}
