/*
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.modelversioning.emfprofile.decoration.ui.internal.EMFProfileDecorationLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EMFProfileDecorationLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EMFProfileDecorationLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EMFProfileDecorationLanguageActivator.getInstance().getInjector(EMFProfileDecorationLanguageActivator.ORG_MODELVERSIONING_EMFPROFILE_DECORATION_EMFPROFILEDECORATIONLANGUAGE);
	}
	
}
