/*
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EMFProfileDecorationLanguageRuntimeModule extends org.modelversioning.emfprofile.decoration.AbstractEMFProfileDecorationLanguageRuntimeModule {

}
