/*
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EMFProfileDecorationLanguageUiModule extends org.modelversioning.emfprofile.decoration.ui.AbstractEMFProfileDecorationLanguageUiModule {
	public EMFProfileDecorationLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
