<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registry" nsURI="http://org.modelversioning/emfprofile/application/registry"
    nsPrefix="par">
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationWrapper">
    <eOperations name="getStereotypeApplications">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getStereotypeApplications">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication"/>
      </eGenericType>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getStereotypeApplications">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication"/>
      </eGenericType>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="stereotype" eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Stereotype"/>
    </eOperations>
    <eOperations name="getAnnotatedObjects">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericType>
    </eOperations>
    <eOperations name="addNestedEObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="container" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      <eParameters name="reference" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="applyStereotype" eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication">
      <eParameters name="stereotypeApplicability" eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplicability"/>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getApplicableStereotypes">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EEList">
        <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplicability"/>
      </eGenericType>
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="getName" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getProfileName" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="isDirty" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="removeEObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eParameters name="eObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="save" eExceptions="#//IOException #//CoreException"/>
    <eOperations name="getProfileApplicationIFile" eType="#//IFile"/>
    <eOperations name="getProfileApplicationResource" eType="#//Resource"/>
    <eOperations name="unload"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileApplication" lowerBound="1"
        eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//ProfileApplication"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationRegistry">
    <eOperations name="getProfileApplicationManager" eType="#//ProfileApplicationManager"
        eExceptions="#//NullPointerException">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
    </eOperations>
    <eOperations name="getProfileApplicationManager" eType="#//ProfileApplicationManager"
        eExceptions="#//NullPointerException #//ProfileApplicationDecoratorNotFoundException">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
      <eParameters name="editorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="hasProfileApplicationDecoratorForEditorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eParameters name="editorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getProfileApplicationDecoratorForEditorId" eType="#//EMFProfileApplicationDecorator"
        eExceptions="#//NullPointerException #//ProfileApplicationDecoratorNotFoundException">
      <eParameters name="editorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="hasProfileApplicationManager" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        eExceptions="#//NullPointerException">
      <eParameters name="resourceSet" eType="#//ResourceSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managers" ordered="false"
        upperBound="-1" eType="#//ProfileApplicationManager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationManager">
    <eOperations name="createNewProfileApplication" lowerBound="1" eType="#//ProfileApplicationWrapper"
        eExceptions="#//IllegalArgumentException #//IOException #//CoreException">
      <eParameters name="profileApplicationFile" lowerBound="1" eType="#//IFile"/>
      <eParameters name="profiles" lowerBound="1">
        <eGenericType eClassifier="#//Collection">
          <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Profile"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="hasProfileApplications" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="loadProfileApplication" eType="#//ProfileApplicationWrapper"
        eExceptions="#//ProfileApplicationAlreadyLoadedException #//IOException #//CoreException">
      <eParameters name="profileApplicationFile" eType="#//IFile"/>
    </eOperations>
    <eOperations name="dispose"/>
    <eOperations name="getProfileApplicationWrapperOfContainedEObject" eType="#//ProfileApplicationWrapper"
        eExceptions="#//TraversingEObjectContainerChainException">
      <eParameters name="eObject" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="bindProfileApplicationDecorator" eType="#//EMFProfileApplicationDecorator"
        eExceptions="#//NullPointerException #//ProfileApplicationDecoratorNotFoundException">
      <eParameters name="editorId" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileApplications" lowerBound="1"
        upperBound="-1" eType="#//ProfileApplicationWrapper" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IllegalArgumentException" instanceClassName="java.lang.IllegalArgumentException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Resource" instanceClassName="org.eclipse.emf.ecore.resource.Resource"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IFile" instanceClassName="org.eclipse.core.resources.IFile"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOException" instanceClassName="java.io.IOException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ProfileApplicationDecoratorNotFoundException"
      instanceClassName="org.modelversioning.emfprofile.application.registry.exception.ProfileApplicationDecoratorNotFoundException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="NullPointerException" instanceClassName="java.lang.NullPointerException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CoreException" instanceClassName="org.eclipse.core.runtime.CoreException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ProfileApplicationAlreadyLoadedException"
      instanceClassName="org.modelversioning.emfprofile.application.registry.exception.ProfileApplicationAlreadyLoadedException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TraversingEObjectContainerChainException"
      instanceClassName="org.modelversioning.emfprofile.application.registry.exception.TraversingEObjectContainerChainException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  <eClassifiers xsi:type="ecore:EClass" name="EMFProfileApplicationDecorator" abstract="true"
      interface="true">
    <eOperations name="canDecorateEditorsWithFollowingIDs">
      <eGenericType eClassifier="#//Collection">
        <eTypeArguments eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eOperations name="decorate">
      <eParameters name="stereotypeApplication" eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication"/>
    </eOperations>
    <eOperations name="undecorate">
      <eParameters name="stereotypeApplication" eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//StereotypeApplication"/>
    </eOperations>
    <eOperations name="resolveEObjectFromEditorSelection" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eParameters name="selection" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
