<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="registry" nsURI="http://org.modelversioning/emfprofile/application/registry"
    nsPrefix="par">
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationWrapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileApplication" lowerBound="1"
        eType="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofileapplication.ecore#//ProfileApplication"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationRegistry">
    <eOperations name="createNewProfileApplication" lowerBound="1" eType="#//ProfileApplicationWrapper"
        eExceptions="#//IllegalArgumentException #//IOException #//CoreException">
      <eParameters name="resourceSet" eType="#//ResourceSet"/>
      <eParameters name="profileApplicationFile" lowerBound="1" eType="#//IFile"/>
      <eParameters name="profiles" lowerBound="1">
        <eGenericType eClassifier="#//Collection">
          <eTypeArguments eClassifier="ecore:EClass ../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Profile"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="loadProfileApplication" eType="#//ProfileApplicationWrapper"
        eExceptions="#//ProfileApplicationAlreadyLoadedException #//IOException #//CoreException">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
      <eParameters name="profileApplicationFile" eType="#//IFile"/>
    </eOperations>
    <eOperations name="unloadProfileApplication">
      <eParameters name="profileApplication" lowerBound="1" eType="#//ProfileApplicationWrapper"/>
    </eOperations>
    <eOperations name="unloadAllProfileApplications" eExceptions="#//IllegalArgumentException">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
    </eOperations>
    <eOperations name="hasProfileApplications" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        eExceptions="#//IllegalArgumentException">
      <eParameters name="resourceSet" eType="#//ResourceSet"/>
    </eOperations>
    <eOperations name="getProfileApplications" lowerBound="1" eExceptions="#//IllegalArgumentException">
      <eGenericType eClassifier="#//Collection">
        <eTypeArguments eClassifier="#//ProfileApplicationWrapper"/>
      </eGenericType>
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
    </eOperations>
    <eOperations name="getProfileApplicationWrapperOfContainedEObject" eType="#//ProfileApplicationWrapper"
        eExceptions="#//TraversingEObjectContainerChainException #//IllegalArgumentException">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
      <eParameters name="eobject" lowerBound="1" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="getProfileApplicationManager" eType="#//ProfileApplicationManager">
      <eParameters name="resourceSet" lowerBound="1" eType="#//ResourceSet"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managers" ordered="false"
        upperBound="-1" eType="#//ProfileApplicationManager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplicationManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profileApplications" lowerBound="1"
        upperBound="-1" eType="#//ProfileApplicationWrapper" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IllegalArgumentException" instanceClassName="java.lang.IllegalArgumentException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ResourceSet" instanceClassName="org.eclipse.emf.ecore.resource.ResourceSet"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IFile" instanceClassName="org.eclipse.core.resources.IFile"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOException" instanceClassName="java.io.IOException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CoreException" instanceClassName="org.eclipse.core.runtime.CoreException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ProfileApplicationAlreadyLoadedException"
      instanceClassName="org.modelversioning.emfprofile.application.registry.exception.ProfileApplicationAlreadyLoadedException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TraversingEObjectContainerChainException"
      instanceClassName="org.modelversioning.emfprofile.application.registry.exception.TraversingEObjectContainerChainException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
</ecore:EPackage>
