<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="decorationLanguage" nsURI="http://www.modelversioning.org/emfprofile/decoration/EMFProfileDecorationLanguage"
    nsPrefix="decorationLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="DecorationModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorationDescriptions"
        upperBound="-1" eType="#//DecorationDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="profile" eType="ecore:EClass ../../../../../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Profile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecorationDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" eType="ecore:EClass ../../../../../../org.modelversioning.emfprofile/model/emfprofiles.ecore#//Stereotype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorations" upperBound="-1"
        eType="#//AbstractDecoration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" eType="#//Activation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" eType="#//Activation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageDecoration" eSuperTypes="#//AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location_uri" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="direction" eType="#//Direction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="margin" eType="#//Margin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tooltip" eType="#//Text"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoxDecoration" eSuperTypes="#//AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//Text" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" eType="#//BoxImage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//Border"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foregroundColor" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundColor" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="direction" eType="#//Direction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="margin" eType="#//Margin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentDirection" eType="#//Directions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tooltip" eType="#//Text"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BorderDecoration" eSuperTypes="#//AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//Border"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorDecoration" eSuperTypes="#//AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreground" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionDecoration" eSuperTypes="#//AbstractDecoration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//Style"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleText" eSuperTypes="#//Text">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexText" eSuperTypes="#//Text">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//SimpleText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Text"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Border">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//Style"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoxImage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location_uri" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placement" eType="#//BoxImageOrientation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//LineStyle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Direction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Directions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Margin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ColorConstant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concrete" eType="#//ConcreteColor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteColor"/>
  <eClassifiers xsi:type="ecore:EClass" name="RGB" eSuperTypes="#//ConcreteColor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HexColor" eSuperTypes="#//ConcreteColor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hexCode" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorConstant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Colors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//AbstractCondition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="OclExpression" eSuperTypes="#//AbstractCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//AbstractCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType ../../../../../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeCondition" eSuperTypes="#//AbstractCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//LogicalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//AbstractCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoxImageOrientation">
    <eLiterals name="WEST" literal="WEST"/>
    <eLiterals name="NORTH" value="1" literal="NORTH"/>
    <eLiterals name="EAST" value="2" literal="EAST"/>
    <eLiterals name="SOUTH" value="3" literal="SOUTH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="EQUAL" literal="=="/>
    <eLiterals name="UNEQUAL" value="1" literal="!="/>
    <eLiterals name="GREATER" value="2" literal=">"/>
    <eLiterals name="GREATEROREQUAL" value="3" literal=">="/>
    <eLiterals name="LOWER" value="4" literal="&lt;"/>
    <eLiterals name="LOWEROREQUAL" value="5" literal="&lt;="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperator">
    <eLiterals name="ALL" literal="ALL"/>
    <eLiterals name="ANY" value="1" literal="ANY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LineStyle">
    <eLiterals name="LINE_SOLID" literal="SOLID"/>
    <eLiterals name="LINE_DOT" value="1" literal="DOTS"/>
    <eLiterals name="LINE_DASH" value="2" literal="DASH"/>
    <eLiterals name="LINE_DASHDOT" value="3" literal="DASHDOT"/>
    <eLiterals name="LINE_DASHDOTDOT" value="4" literal="DASHDOTDOT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Colors">
    <eLiterals name="RED" literal="RED"/>
    <eLiterals name="BLACK" value="1" literal="BLACK"/>
    <eLiterals name="WHITE" value="2" literal="WHITE"/>
    <eLiterals name="GREEN" value="3" literal="GREEN"/>
    <eLiterals name="GREEN_LIGHT" value="4" literal="GREEN_LIGHT"/>
    <eLiterals name="GREEN_DARK" value="5" literal="GREEN_DARK"/>
    <eLiterals name="BLUE" value="6" literal="BLUE"/>
    <eLiterals name="BLUE_LIGHT" value="7" literal="BLUE_LIGHT"/>
    <eLiterals name="BLUE_DARK" value="8" literal="BLUE_DARK"/>
    <eLiterals name="GRAY" value="9" literal="GRAY"/>
    <eLiterals name="GRAY_LIGHT" value="10" literal="GRAY_LIGHT"/>
    <eLiterals name="GRAY_DARK" value="11" literal="GRAY_DARK"/>
    <eLiterals name="ORANGE" value="12" literal="ORANGE"/>
    <eLiterals name="YELLOW" value="13" literal="YELLOW"/>
    <eLiterals name="CYAN" value="14" literal="CYAN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Directions">
    <eLiterals name="CENTER" literal="CENTER"/>
    <eLiterals name="NORTH" value="1" literal="NORTH"/>
    <eLiterals name="SOUTH" value="2" literal="SOUTH"/>
    <eLiterals name="WEST" value="3" literal="WEST"/>
    <eLiterals name="EAST" value="4" literal="EAST"/>
    <eLiterals name="NORTH_EAST" value="5" literal="NORTH_EAST"/>
    <eLiterals name="NORTH_WEST" value="6" literal="NORTH_WEST"/>
    <eLiterals name="SOUTH_EAST" value="7" literal="SOUTH_EAST"/>
    <eLiterals name="SOUTH_WEST" value="8" literal="SOUTH_WEST"/>
  </eClassifiers>
</ecore:EPackage>
