/*
 * generated by Xtext
 */
package org.modelversioning.emfprofile.decoration.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractEMFProfileDecorationLanguageValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.modelversioning.emfprofile.decoration.decorationLanguage.DecorationLanguagePackage.eINSTANCE);
		return result;
	}
}
